language: java
jdk: oraclejdk8
before_install:
  - nvm install 4
  - npm install
  - npm install -g grunt-cli
script:
  - ./gradlew build -x ktlint
  - ./gradlew ktlint
  - grunt test
after_success:
  - ./gradlew dokka
  - grunt dist
cache:
  directories:
    - node_modules/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  on:
    branch: master
